name = "The Thing"
author = "LaCosa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ba7b4b38479882f5f0a7680ef8d31531433273b4a65d4cc4ab00955754300a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
