name = "The Thing"
author = "LaCosa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "283481a809a57787ed3159c4cc02f2d15e4eee63f5238071be1fae13a9f849f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
