name = "The Thing"
author = "LaCosa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8725240b0cf9d2265499897d42460448c305dc2473e089a90932bd26ff623679"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
