name = "The Thing"
author = "LaCosa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "106c5de425f28405ea61eb536804946313bc4f90a129f022a56ee6270af18a32"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
