name = "The Thing"
author = "LaCosa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "173d4809e804e344ee20389cfb1d7d5910cd61328f37bc74b6b22be8585172c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
