[Season]
        #The lasting days of each term, while 4 seasons in 1 year, 6 terms in 1 season.
        # Default: 7
        # Range: 1 ~ 5000
        LastingDaysOfEachTerm = 7
        #The index of the initial solar term, and note it only can be used to first start the world with the mod.
        # Default: 4
        # Range: 1 ~ 24
        InitialSolarTermIndex = 4
        #Enable solar term change inform.
        EnableInform = true
        #Whether send inform with icon.
        EnableInformIcon = true
        #Whether to pop up the solar term reminder when the calendar item cannot be placed.
        CalendarItemHint = false
        #In summer, the days are long and the nights are short, while in winter, the days are short and the nights are long.
        DynamicDaylightDuration = true
        #Which dimensions will have season effects? Note that it must be natrual and have time lapse.
        ValidDimensions = ["minecraft:overworld"]
        #If snow falls during cold weather in warm biomes, it will gradually cover all solid blocks and grass.
        SnowyWinter = true
        #Snow will not appear in overly bright areas, here define restriction levels.
        NotSnowyNearGlowingBlock = true
        #Snow will not appear in overly bright areas.
        # Default: 10
        # Range: 1 ~ 15
        NotSnowyNearGlowingBlockLevel = 10

[Weather]
        #Enable solar term weather system with biome.
        UseSolarWeather = true
        #Set it true to initialize weather and snow when loading the mod or level for the first time.
        ShouldInitWeather = false
        #Set the percentage multiplier of the probability of rain, the range should be between 0 and 1000.
        # Default: 40
        # Range: 0 ~ 1000
        RainChancePercentMultiplier = 40
        #Set the percentage multiplier of the probability of thunder in the rain, the range should be between 0 and 1000.
        # Default: 20
        # Range: 0 ~ 1000
        ThunderChancePercentMultiplier = 20

[Temperature]
        #Ice or snow layer will melt in warm time.
        IceAndSnowMelt = true
        #It will snow in cold time.
        IceAndSnow = true
        #Add heat stroke effect in summer noon while in hot biome.
        HeatStroke = false

[Crop]
        #Enable crop season control.
        EnableSeasonalCrop = true
        #How much grow_chance can crop grow in wrong season.
        # Default: 0.25
        # Range: 0.0 ~ 1.0
        "[Deprecated]CropGrowChanceInWrongSeason" = 0.25
        #Enable crop humidity control.
        EnableCropHumidityControl = true
        #How much base grow_chance can crop grow in wrong humidity.
        # Default: 0.25
        # Range: 1.0E-4 ~ 0.9999
        "[Deprecated]CropGrowChanceInWrongHumidity" = 0.25
        #The maximum effective diameter of the greenhouse.
        # Default: 32
        # Range: 5 ~ 256
        GreenHouseMaxDiameter = 32
        #The maximum effective diameter of the greenhouse.
        # Default: 10
        # Range: 3 ~ 128
        GreenHouseMaxHeight = 10
        #The possibility of crops not growing when there is insufficient sunlight in green house.
        # Default: 2000
        # Range: 0 ~ 10000
        DarkGreenhouseFailChance = 2000
        #Build a simple greenhouse without core blocks and humidity modifiers.
        SimpleGreenHouseMode = false
        #Enabled to make the Humidifier stop converting inputs/outputs.
        NoCostHumidifier = false
        #Whether to enable complex shape checking.
        ComplexGreenHouseCheck = true
        #[Deprecated]If a crop is not registered for a season or humid type, default values will be used.
        RegisterCropDefaultValue = false
        #Force all crops to use compatibility mode for growth control, not just those tagged as eclipticseasons:natural_plants.
        ForceCompatMode = false

[Animal]
        #Enable seasonal animal breed.
        EnableSeasonalBreed = false
        #Enable seasonal bee behavior, bee would like spring and not like winter and cold.
        EnableSeasonalBee = false
        #Enable seasonal fishing behavior, let enjoy summer.
        EnableSeasonalFishing = false

[Map]
        #When snow falls, the top block does not immediately become snowy if the height map change.
        ServerRealisticSnowyChange = true
        #The map color of blocks will change during snow.
        ChangeMapColor = true

[Compat]
        #Compatible with mods using SereneSeasons' CropTag.
        SereneSeasonsCropTag = true

[Debug]
        #Enable debug option to detect illegal use of functions.
        LogIllegalUse = false
        #Without snowy block under the light blocks which level is 0.
        NoSnowyUnderLight0 = false
        #Snow overlay block if has full collision shape not just full render shape.
        SnowyFullCollisionShape = false
        #Snow can cover the block which would lights.
        SnowOverlayGlowingBlock = false
        #Set to false to disable tag which stops block from snowy is tagged with "eclipticseasons:snow_overlay_cannot_survive_on".
        DisableSnowOverlayControlTag = false
